version: 'build_{build}'

image:
- Visual Studio 2017
- Visual Studio 2015

clone_depth: 1
clone_folder: c:\projects\scope_guard

environment:
  CATCH_DIR: c:\projects\catch
  CATCH_REMOTE: https://github.com/catchorg/Catch2.git

install:
  - git clone %CATCH_REMOTE% %CATCH_DIR%
  - cd %CATCH_DIR%
  - pwsh: git checkout -q $(git describe --tags --abbrev=0)
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING:BOOL=FALSE ..
  - cmake --build .
  - cmake --build . --target install
  - cd %APPVEYOR_BUILD_FOLDER% # reset current directory

build:
  verbosity: normal
